# Generated by Django 3.2.5 on 2021-07-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_alter_itemlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
